apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: node-github-actions-quay-060625x
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-github-actions-quay-060625x 
  name: node-github-actions-quay-060625x
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: node-github-actions-quay-060625x 
